### ISSUE TITLE
Group TODO List

### ISSUE THREAD

**Issue by lmoraguez** [lmoraguez/PetAdoption-API#1]
- [ ] Link app to Azure (via Web Conference)
- [ ] Create Database Project (via Web Conference)
- [ ] Identify the calls (gets, puts, deletes, posts, etc)
