### ISSUE TITLE
Luis' TODO List

### ISSUE THREAD

**Issue by lmoraguez** [lmoraguez/PetAdoption-API#2]
- [x] Set up Git Repo - <i>Completed - LMM</i>
- [x] Initial Commit - <i>Completed - LMM</i>
- [x] Set up Default App Scaffolding - <i>Completed - LMM</i>
- [x] Commit Scaffolding to Git - <i>Completed - LMM</i>
- [ ] Set up Azure account
